export const properties = [
  {
    id: 1,
    address: "123 Main Street, Damascus",
    location: "Damascus, Syria",
    minutes: 10,
    project: "Al Qasr Residences",
    img: ["/images/2012-11.webp"],
    area: 180,
    state: "for sale",
    video: "/videos/house1.mp4",
    numOfRoom: 4,
    numOfBath: 3,
    numOfBalconi: 2,
    description: "A modern family apartment with a great view and spacious rooms.",
    procondition: "Excellent",
  },
  {
    id: 2,
    address: "45 Coastal Road, Tartous",
    location: "Tartous, Syria",
    minutes: 5,
    project: "Sea View Villas",
    img: ["/images/ae205a50-53b3-11ec-9aff-3d50541531a0-luxury-property.jpg"],
    area: 250,
    state: "for rent",
    video: "/videos/house2.mp4",
    numOfRoom: 5,
    numOfBath: 4,
    numOfBalconi: 3,
    description: "Luxury villa with direct sea access and private garden.",
    procondition: "Very Good",
  },
  {
    id: 3,
    address: "45 Coastal Road, Tartous",
    location: "Tartous, Syria",
    minutes: 5,
    project: "Sea View Villas",
    img: ["/images/villa-cover-Ae-240522.jpg"],
    area: 250,
    state: "for rent",
    video: "/videos/house2.mp4",
    numOfRoom: 5,
    numOfBath: 4,
    numOfBalconi: 3,
    description: "Luxury villa with direct sea access and private garden.",
    procondition: "Very Good",
  },
  {
    id: 4,
    address: "45 Coastal Road, Tartous",
    location: "Tartous, Syria",
    minutes: 5,
    project: "Sea View Villas",
    img: ["/images/Vivaldi_125.webp"],
    area: 250,
    state: "for rent",
    video4: "/videos/house2.mp4",
    numOfRoom: 5,
    numOfBath: 4,
    numOfBalconi: 3,
    description: "Luxury villa with direct sea access and private garden.",
    procondition: "Very Good",
  },
  {
    id: 5,
    address: "45 Coastal Road, Tartous",
    location: "Tartous, Syria",
    minutes: 5,
    project: "Sea View Villas",
    img: ["/images/SL-toddwilson041-ed381b825b954c7b9ed4749ed4d7deb5.jpeg"],
    area: 250,
    state: "for rent",
    video: "/videos/house2.mp4",
    numOfRoom: 5,
    numOfBath: 4,
    numOfBalconi: 3,
    description: "Luxury villa with direct sea access and private garden.",
    procondition: "Very Good",
  },
  {
    id: 6,
    address: "45 Coastal Road, Tartous",
    location: "Tartous, Syria",
    minutes: 5,
    project: "Sea View Villas",
    img: ["/images/w800x533.jpg"],
    area: 250,
    state: "for rent",
    video: "/videos/house2.mp4",
    numOfRoom: 5,
    numOfBath: 4,
    numOfBalconi: 3,
    description: "Luxury villa with direct sea access and private garden.",
    procondition: "Very Good",
  },
  {
    id: 7,
    address: "45 Coastal Road, Tartous",
    location: "Tartous, Syria",
    minutes: 5,
    project: "Sea View Villas",
    img: ["/images/w991x660.jpg"],
    area: 250,
    state: "for rent",
    video: "/videos/house2.mp4",
    numOfRoom: 5,
    numOfBath: 4,
    numOfBalconi: 3,
    description: "Luxury villa with direct sea access and private garden.",
    procondition: "Very Good",
  },
  {
    id: 8,
    address: "45 Coastal Road, Tartous",
    location: "Tartous, Syria",
    minutes: 5,
    project: "Sea View Villas",
    img: ["/images/w800x533.jpg"],
    area: 250,
    state: "for rent",
    video: "/videos/house2.mp4",
    numOfRoom: 5,
    numOfBath: 4,
    numOfBalconi: 3,
    description: "Luxury villa with direct sea access and private garden.",
    procondition: "Very Good",
  },
  {
    id: 9,
    address: "45 Coastal Road, Tartous",
    location: "Tartous, Syria",
    minutes: 5,
    project: "Sea View Villas",
    img: ["/images/w991x660.jpg"],
    area: 250,
    state: "for rent",
    video: "/videos/house2.mp4",
    numOfRoom: 5,
    numOfBath: 4,
    numOfBalconi: 3,
    description: "Luxury villa with direct sea access and private garden.",
    procondition: "Very Good",
  },
  {
    id: 10,
    address: "45 Coastal Road, Tartous",
    location: "Tartous, Syria",
    minutes: 5,
    project: "Sea View Villas",
    img: ["/images/w800x533.jpg"],
    area: 250,
    state: "for rent",
    video: "/videos/house2.mp4",
    numOfRoom: 5,
    numOfBath: 4,
    numOfBalconi: 3,
    description: "Luxury villa with direct sea access and private garden.",
    procondition: "Very Good",
  },
  {
    id: 11,
    address: "45 Coastal Road, Tartous",
    location: "Tartous, Syria",
    minutes: 5,
    project: "Sea View Villas",
    img: ["/images/141429.jpg"],
    area: 250,
    state: "for rent",
    video: "/videos/house2.mp4",
    numOfRoom: 5,
    numOfBath: 4,
    numOfBalconi: 3,
    description: "Luxury villa with direct sea access and private garden.",
    procondition: "Very Good",
  },
  {
    id: 12,
    address: "45 Coastal Road, Tartous",
    location: "Tartous, Syria",
    minutes: 5,
    project: "Sea View Villas",
    img: ["/images/FONDS_GOUVART-_21.webp"],
    area: 250,
    state: "for rent",
    video: "/videos/house2.mp4",
    numOfRoom: 5,
    numOfBath: 4,
    numOfBalconi: 3,
    description: "Luxury villa with direct sea access and private garden.",
    procondition: "Very Good",
  },
  {
    id: 13,
    address: "45 Coastal Road, Tartous",
    location: "Tartous, Syria",
    minutes: 5,
    project: "Sea View Villas",
    img: ["/images/2012-11.webp"],
    area: 250,
    state: "for rent",
    video: "/videos/house2.mp4",
    numOfRoom: 5,
    numOfBath: 4,
    numOfBalconi: 3,
    description: "Luxury villa with direct sea access and private garden.",
    procondition: "Very Good",
  },
  {
    id: 14,
    address: "45 Coastal Road, Tartous",
    location: "Tartous, Syria",
    minutes: 5,
    project: "Sea View Villas",
    img: ["/images/141429.jpg"],
    area: 250,
    state: "for rent",
    video: "/videos/house2.mp4",
    numOfRoom: 5,
    numOfBath: 4,
    numOfBalconi: 3,
    description: "Luxury villa with direct sea access and private garden.",
    procondition: "Very Good",
  },
    {
    id: 15,
    address: "45 Coastal Road, Tartous",
    location: "Tartous, Syria",
    minutes: 5,
    project: "Sea View Villas",
    img: ["/images/FONDS_GOUVART-_21.webp"],
    area: 250,
    state: "for rent",
    video: "/videos/house2.mp4",
    numOfRoom: 5,
    numOfBath: 4,
    numOfBalconi: 3,
    description: "Luxury villa with direct sea access and private garden.",
    procondition: "Very Good",
  },
  {
    id: 16,
    address: "45 Coastal Road, Tartous",
    location: "Tartous, Syria",
    minutes: 5,
    project: "Sea View Villas",
    img: ["/images/w800x533.jpg"],
    area: 250,
    state: "for rent",
    video: "/videos/house2.mp4",
    numOfRoom: 5,
    numOfBath: 4,
    numOfBalconi: 3,
    description: "Luxury villa with direct sea access and private garden.",
    procondition: "Very Good",
  }
];
